<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>JavaScript</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.JavaScript</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="JavaScriptParser\**" />
    <EmbeddedResource Remove="JavaScriptParser\**" />
    <None Remove="JavaScriptParser\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="App.ico" />
    <Content Include="QuickSort.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="JavaScriptParser\JavaScriptParser.csproj" />
  </ItemGroup>
</Project>