<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Entities</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.Entities</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\0.png" />
    <Resource Include="Files\1.png" />
    <Resource Include="Files\2.png" />
    <Resource Include="Files\3.png" />
    <Resource Include="Files\4.png" />
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>