<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>OrgChartEditor</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.OrgChartEditor</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="App.ico" />
    <Resource Include="Images\ad.png" />
    <Resource Include="Images\ceo.png" />
    <Resource Include="Images\cto.png" />
    <Resource Include="Images\hr.png" />
    <Resource Include="Images\team-placeholder.jpg" />
  </ItemGroup>
</Project>