<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Tutorial3</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.Tutorial3</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="016.png"></Resource>
    <Resource Include="ac0026-64.png"></Resource>
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>