<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>JavaScriptParser</RootNamespace>
    <AssemblyName>JavaScriptParser</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configurations>Release;Debug</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;TRACE;CORE;Net5</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\Release</OutputPath>
    <DefineConstants>CORE;Net5</DefineConstants>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <None Include="JavaScript.g" />
    <None Include="JavaScript.tokens" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr" Version="3.1.3.42154" />
  </ItemGroup>
</Project>