<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>IconNodes</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.IconNodes</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="images\ac0006-48.png" />
    <Resource Include="images\ac0011-48.png" />
    <Resource Include="images\ac0048-48.png" />
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>