<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>CustomTemplates</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.CustomTemplates</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="App.ico" />
    <Resource Include="Images\011.png" />
    <Resource Include="Images\012.png" />
    <Resource Include="Images\019.png" />
    <Resource Include="Images\020.png" />
    <Resource Include="Images\026.png" />
    <Resource Include="Images\051.png" />
    <Resource Include="Images\057.png" />
    <Resource Include="Images\058.png" />
  </ItemGroup>
</Project>