<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Demo</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.Demo</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>Files\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Files\VisioStencils\**" />
    <EmbeddedResource Remove="Files\VisioStencils\**" />
    <None Remove="Files\VisioStencils\**" />
    <Page Remove="Files\VisioStencils\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Files\Antlr3.Runtime.dll" />
    <None Remove="Files\BasicOperations.xml" />
    <None Remove="Files\Chemical synthesis tree.xml" />
    <None Remove="Files\CircularLayout.xml" />
    <None Remove="Files\Class-hierarchy.xml" />
    <None Remove="Files\Classification chart.xml" />
    <None Remove="Files\ClusteredLayout.xml" />
    <None Remove="Files\Containers.xml" />
    <None Remove="Files\CustomDrawLinks.xml" />
    <None Remove="Files\DatabaseRelationshipDiagram.xml" />
    <None Remove="Files\Demo.exe" />
    <None Remove="Files\Demo.exe.config" />
    <None Remove="Files\Demo.pdb" />
    <None Remove="Files\Demo.vshost.exe" />
    <None Remove="Files\Demo.vshost.exe.config" />
    <None Remove="Files\Demo.vshost.exe.manifest" />
    <None Remove="Files\Dialogue chart.xml" />
    <None Remove="Files\Drag and drop.xml" />
    <None Remove="Files\dummy1.png" />
    <None Remove="Files\dummy2.png" />
    <None Remove="Files\dummy3.png" />
    <None Remove="Files\ERM.xml" />
    <None Remove="Files\FCDemo.exe" />
    <None Remove="Files\FCDemo.pdb" />
    <None Remove="Files\FCDemo.vshost.exe.manifest" />
    <None Remove="Files\Flowchart.xml" />
    <None Remove="Files\FormPreservation.xml" />
    <None Remove="Files\Genealogy tree.xml" />
    <None Remove="Files\GridLayout.xml" />
    <None Remove="Files\Grouping.xml" />
    <None Remove="Files\Heads.xml" />
    <None Remove="Files\Hierarchy chart.xml" />
    <None Remove="Files\JavaScriptParser.dll" />
    <None Remove="Files\LaneDiagram.xml" />
    <None Remove="Files\LayeredLayout.xml" />
    <None Remove="Files\method.png" />
    <None Remove="Files\MindFusion.Barcodes.dll" />
    <None Remove="Files\MindFusion.Common.dll" />
    <None Remove="Files\MindFusion.Common.Wpf.dll" />
    <None Remove="Files\MindFusion.Diagramming.Wpf.dll" />
    <None Remove="Files\MindFusion.Diagramming.Wpf.pdb" />
    <None Remove="Files\MindFusion.Diagramming.Wpf.xml" />
    <None Remove="Files\MindFusion.Graphs.dll" />
    <None Remove="Files\MindFusion.htm" />
    <None Remove="Files\MindFusion.Licensing.dll" />
    <None Remove="Files\MindFusion.Scripting.dll" />
    <None Remove="Files\MindFusion.UI.Wpf.dll" />
    <None Remove="Files\MindFusion.Vsx.dll" />
    <None Remove="Files\NetIco.ico" />
    <None Remove="Files\OneWayLayout.xml" />
    <None Remove="Files\OrthogonalLayoutDiagram.xml" />
    <None Remove="Files\Overview.xml" />
    <None Remove="Files\Owner-draw objects.xml" />
    <None Remove="Files\Pathfinding.xml" />
    <None Remove="Files\People.xml" />
    <None Remove="Files\plus.bmp" />
    <None Remove="Files\property.png" />
    <None Remove="Files\Purchase.htm" />
    <None Remove="Files\Ready diagram.xml" />
    <None Remove="Files\Resources\gender0.png" />
    <None Remove="Files\Resources\gender1.png" />
    <None Remove="Files\Resources\img0.png" />
    <None Remove="Files\Resources\img1.png" />
    <None Remove="Files\Resources\img2.png" />
    <None Remove="Files\Resources\img3.png" />
    <None Remove="Files\Resources\img4.png" />
    <None Remove="Files\Rotation.xml" />
    <None Remove="Files\Rotation2.xml" />
    <None Remove="Files\Routing.xml" />
    <None Remove="Files\Sources.htm" />
    <None Remove="Files\Sources_.htm" />
    <None Remove="Files\SpanningCells.xml" />
    <None Remove="Files\SpringLayout.xml" />
    <None Remove="Files\TextOrientation.xml" />
    <None Remove="Files\Texts.txt" />
    <None Remove="Files\Thumbs.db" />
    <None Remove="Files\TopologicalLayout.xml" />
    <None Remove="Files\TreeLayout.xml" />
    <None Remove="Files\TreeViewNodes.xml" />
    <None Remove="Files\_cs_Purchase.htm" />
    <None Remove="Files\_swreg_Purchase.htm" />
    <None Remove="Files\_wpfpkg_swreg_Purchase.htm" />
    <None Remove="Images\alphaIcon.png" />
    <None Remove="Images\categoryesIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Files\Resources\0.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\6.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\7.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\8.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\backgroundImage.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\backgroundImage3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\del.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\down.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\dragPicture.Image.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\gender0.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\gender1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image0.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\image6.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\img0.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\img1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\img2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\img3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\img4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\plus.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\up.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture10.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture11.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture12.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture13.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture14.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture6.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture7.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture8.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\_picture9.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\cs.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\diagram.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\TreeIcons\1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\TreeIcons\2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\TreeIcons\3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Resources\TreeIcons\4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="App.ico" />
    <Resource Include="Images\alphaIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\categoryesIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="NetIco.ico" />
    <Resource Include="Files\Themes\Aqua.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Themes\Emerald.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Themes\Ruby.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Themes\Slate.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Themes\Vista.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Files\Sources.xml" />
    <Resource Include="Images\topicplus.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\bookclosed.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\bookopen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\topic.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\left.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\right.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
</Project>