//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindFusion.Diagramming.Wpf.Samples.CS.MultiViews.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindFusion.Diagramming.Wpf.Samples.CS.MultiViews.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Diagram Version=&quot;16&quot;&gt;
        ///  &lt;Nodes&gt;
        ///    &lt;Node Class=&quot;std:ShapeNode&quot; Version=&quot;1&quot; Id=&quot;1&quot;&gt;
        ///      &lt;Bounds&gt;65.2799987792969, 99.8399963378906, 138.240005493164, 42.2400016784668&lt;/Bounds&gt;
        ///      &lt;ZIndex&gt;1&lt;/ZIndex&gt;
        ///      &lt;LayerIndex&gt;-1&lt;/LayerIndex&gt;
        ///      &lt;HyperLink&gt;
        ///      &lt;/HyperLink&gt;
        ///      &lt;Locked&gt;False&lt;/Locked&gt;
        ///      &lt;Visible&gt;True&lt;/Visible&gt;
        ///      &lt;Printable&gt;True&lt;/Printable&gt;
        ///      &lt;Brush Id=&quot;2&quot; /&gt;
        ///      &lt;Weight&gt;1&lt;/Weight&gt;
        ///      &lt;IgnoreLayout&gt;False&lt;/IgnoreLayout&gt;
        ///      &lt;Text&gt;START&lt;/Text&gt;
        ///      &lt;TextColo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flowchart {
            get {
                return ResourceManager.GetString("Flowchart", resourceCulture);
            }
        }
    }
}
