<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>FlowCharter</AssemblyName>
    <RootNamespace>MindFusion.Diagramming.Wpf.Samples.CS.FlowCharter</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MindFusion.Diagramming.Wpf" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\App.ico" />
    <Resource Include="Icons\Circle.ico" />
    <Resource Include="Icons\Rect.ico" />
    <Resource Include="Icons\X.ico" />
    <Resource Include="App.ico" />
  </ItemGroup>
</Project>